# syntax=docker/dockerfile:1
# Razvojni Dockerfile — brez BUNDLE_DEPLOYMENT, omogoča sproten `bundle install`
# ob spremembi Gemfile. Uporablja ga docker-compose.yml.

ARG RUBY_VERSION=3.4.2
FROM docker.io/library/ruby:$RUBY_VERSION-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    curl libjemalloc2 libvips postgresql-client \
    tesseract-ocr tesseract-ocr-slv tesseract-ocr-hun poppler-utils \
    build-essential git libpq-dev libyaml-dev pkg-config \
    imagemagick && \
    ln -s /usr/lib/$(uname -m)-linux-gnu/libjemalloc.so.2 /usr/local/lib/libjemalloc.so && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV BUNDLE_PATH="/usr/local/bundle" \
    LD_PRELOAD="/usr/local/lib/libjemalloc.so"

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
